image:
  repository: mi-registro/mi-aplicacion
  tag: v1
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: mi-aplicacion.dominio.com

serviceAccount:
  create: true
  name: ""
  automount: true
  annotations: {}

